language: node_js
node_js:
  - '8'
cache: yarn
before_instal:
  - openssl aes-256-cbc -K $encrypted_33b1ef91d91b_key -iv $encrypted_33b1ef91d91b_iv -in deploy_key.pem.enc -out deploy_key.pem -d
script:
  - yarn check --integrity
  - yarn test
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/deploy_key.pem
  - ssh-add .travis/deploy_key.pem
  - git remote add deploy $HOST_URL
  - git push deploy master --quiet
