language: node_js
node_js:
- '10'
cache: yarn
git:
  submodules: false
before_install:
- yarn global add greenkeeper-lockfile@1
- sed -i "s/git@github.com:/https:\/\/andreiconstantinescu:$GITHUB_TOKEN@github.com\//" .gitmodules
- git submodule update --init --recursive
before_script: greenkeeper-lockfile-update
script:
- yarn check --integrity
- yarn test
- yarn build
- yarn submodule:update
after_script: greenkeeper-lockfile-upload
before_deploy:
- git config --global user.email "andrei+travis@constantinescu.io"
- git config --global user.name "Travis CI"
- export RELEASE_VERSION=1.0.$TRAVIS_BUILD_NUMBER
- yarn config set version-git-message "Build v%s."
deploy:
  provider: script
  script: "./deploy.sh"
  skip_cleanup: true
  on:
    branch: master
after_deploy:
  - git add out/
  - git commit -m 'Update submodules.'
  - git push -q https://andreiconstantinescu:$GITHUB_TOKEN@github.com/andreiconstantinescu/constantinescu.io
  - yarn version --new-version $RELEASE_VERSION
  - git push -q https://andreiconstantinescu:$GITHUB_TOKEN@github.com/andreiconstantinescu/constantinescu.io --tags
branches:
  only:
  - master
  - /^greenkeeper/.*$/
