language: 'node_js'
node_js:
- 10
cache: yarn
before_install:
- openssl aes-256-cbc -K $encrypted_c6b17e88fa55_key -iv $encrypted_c6b17e88fa55_iv
  -in ./.travis/keys/deploy.key.enc -out ./.travis/keys/deploy.key -d
- yarn global add greenkeeper-lockfile@1
- chmod +x ./.travis/hooks/deploy.sh
- chmod +x ./.travis/hooks/after-deploy.sh
before_script: greenkeeper-lockfile-update
install:
- git fetch --unshallow --tags
script:
- yarn test
after_script: greenkeeper-lockfile-upload
deploy:
  provider: script
  script: "./.travis/hooks/deploy.sh"
  skip_cleanup: true
  on:
    branch: master
after_deploy:
- ./.travis/hooks/after-deploy.sh
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
