language: node_js
node_js:
  - '8'
cache: yarn
before_install:
  - openssl aes-256-cbc -K $encrypted_33b1ef91d91b_key -iv $encrypted_33b1ef91d91b_iv -in .travis/deploy_key.pem.enc -out .travis/deploy_key.pem -d
  - echo -e "Host $HOST_URL\n\tStrictHostKeyChecking no\nLogLevel ERROR\n" >> ~/.ssh/config
script:
  - yarn check --integrity
  - yarn test
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: master
