version: 2.1

executors:
  nodejs:
    docker:
      - image: circleci/node:11.11
    working_directory: ~/repo

commands:
  install-deps:
    steps:
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --production=false
  restore-caches:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - restore_cache:
          name: Restore node_modules Cache
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
  save-caches:
    steps:
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          name: Save node_modules Cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  build:
    executor: nodejs
    steps:
      - checkout
      - restore-caches
      - install-deps
      - save-caches
  deploy-gh-pages:
    executor: nodejs
      steps:
        - add_ssh_keys:
            fingerprints:
              - "45:5e:a1:63:63:c1:7b:ce:e4:99:b4:44:c8:ab:95:20"
        - checkout
        - restore-caches

workflows:
  build-deploy/gh-pages:
    jobs:
      - build
      - deploy-gh-pages:
          requires:
            - build
          filters:
            branches:
              only: master
